// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Opens a new account for the authenticated requester with a 0 balance in the given currency.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Open a new account",
                "parameters": [
                    {
                        "description": "Owner email and currency",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The account was created.",
                        "schema": {
                            "$ref": "#/definitions/http.CreateAccountResponse"
                        }
                    },
                    "400": {
                        "description": "Request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `) — e.g. an invalid or missing email.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the account only if it belongs to the authenticated requester.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Look up an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The account was found.",
                        "schema": {
                            "$ref": "#/definitions/http.GetAccountResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists with the given ` + "`" + `id` + "`" + ` for this requester (` + "`" + `ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{id}/close": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently closes an account. The balance must be exactly 0 first (withdraw or transfer out any remaining funds).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Close an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "The account was closed."
                    },
                    "400": {
                        "description": "One of: the account is already closed (` + "`" + `ACCOUNT_ALREADY_CLOSED` + "`" + `), or the balance is not 0 (` + "`" + `ACCOUNT_BALANCE_NOT_ZERO` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists with the given ` + "`" + `id` + "`" + ` for this requester (` + "`" + `ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{id}/deposit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Credits the given amount to the account and records a ` + "`" + `DEPOSIT` + "`" + ` transaction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Deposit money into an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Deposit amount",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.DepositRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The deposit succeeded.",
                        "schema": {
                            "$ref": "#/definitions/http.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "One of: request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `), the amount is not a positive integer (` + "`" + `ACCOUNT_INVALID_AMOUNT` + "`" + `), or the account is not active (` + "`" + `ACCOUNT_DEPOSIT_REQUIRES_ACTIVE_ACCOUNT` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists with the given ` + "`" + `id` + "`" + ` for this requester (` + "`" + `ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{id}/reactivate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Moves a suspended account back to active, restoring its ability to accept deposits/withdrawals/transfers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Reactivate a suspended account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "The account was reactivated."
                    },
                    "400": {
                        "description": "Only a suspended account can be reactivated (` + "`" + `ACCOUNT_REACTIVATE_REQUIRES_SUSPENDED_ACCOUNT` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists with the given ` + "`" + `id` + "`" + ` for this requester (` + "`" + `ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{id}/suspend": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Suspends an active account, blocking further deposits/withdrawals/transfers until it is reactivated.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Suspend an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "The account was suspended."
                    },
                    "400": {
                        "description": "Only an active account can be suspended (` + "`" + `ACCOUNT_SUSPEND_REQUIRES_ACTIVE_ACCOUNT` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists with the given ` + "`" + `id` + "`" + ` for this requester (` + "`" + `ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{id}/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the account's deposit/withdrawal/interest transactions, newest first, paginated with ` + "`" + `page` + "`" + `/` + "`" + `take` + "`" + `. Out-of-range ` + "`" + `page` + "`" + `/` + "`" + `take` + "`" + ` values fall back to their defaults rather than failing.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "List an account's transaction history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page number, starting at 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "take",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The transaction history was found.",
                        "schema": {
                            "$ref": "#/definitions/http.GetTransactionsResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists with the given ` + "`" + `id` + "`" + ` for this requester (` + "`" + `ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{id}/transfer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atomically debits the source account and credits the target account with the given amount, recording one ` + "`" + `WITHDRAWAL` + "`" + ` and one ` + "`" + `DEPOSIT` + "`" + ` transaction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Transfer money to another account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The source account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Target account and transfer amount",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The transfer succeeded.",
                        "schema": {
                            "$ref": "#/definitions/http.TransferResponse"
                        }
                    },
                    "400": {
                        "description": "One of: request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `), the amount is not a positive integer (` + "`" + `ACCOUNT_INVALID_AMOUNT` + "`" + `), the source and target accounts are the same (` + "`" + `ACCOUNT_TRANSFER_SAME_ACCOUNT` + "`" + `), either account is not active (` + "`" + `ACCOUNT_WITHDRAW_REQUIRES_ACTIVE_ACCOUNT` + "`" + `/` + "`" + `ACCOUNT_DEPOSIT_REQUIRES_ACTIVE_ACCOUNT` + "`" + `), the currencies do not match (` + "`" + `ACCOUNT_CURRENCY_MISMATCH` + "`" + `), or the balance is insufficient (` + "`" + `ACCOUNT_INSUFFICIENT_BALANCE` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists with the given source or target account ID (` + "`" + `ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{id}/withdraw": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Debits the given amount from the account and records a ` + "`" + `WITHDRAWAL` + "`" + ` transaction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Withdraw money from an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Withdrawal amount",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.WithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The withdrawal succeeded.",
                        "schema": {
                            "$ref": "#/definitions/http.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "One of: request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `), the amount is not a positive integer (` + "`" + `ACCOUNT_INVALID_AMOUNT` + "`" + `), the account is not active (` + "`" + `ACCOUNT_WITHDRAW_REQUIRES_ACTIVE_ACCOUNT` + "`" + `), or the balance is insufficient (` + "`" + `ACCOUNT_INSUFFICIENT_BALANCE` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists with the given ` + "`" + `id` + "`" + ` for this requester (` + "`" + `ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "description": "Verifies the user ID/password and issues a JWT bearer token. Responds with the same error whether the user ID doesn't exist or the password is wrong, to prevent user enumeration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign in",
                "parameters": [
                    {
                        "description": "User ID and password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "A bearer token was issued.",
                        "schema": {
                            "$ref": "#/definitions/http.SignInResponse"
                        }
                    },
                    "400": {
                        "description": "Request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `) — e.g. a missing ` + "`" + `userId` + "`" + `/` + "`" + `password` + "`" + `.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The user ID doesn't exist, or the password doesn't match (` + "`" + `INVALID_CREDENTIALS` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/sign-up": {
            "post": {
                "description": "Registers a new user ID with a password. The password is hashed before storage; the plaintext is never persisted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign up",
                "parameters": [
                    {
                        "description": "New user ID and password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The user was registered."
                    },
                    "400": {
                        "description": "One of: request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `) — e.g. a missing ` + "`" + `userId` + "`" + ` or a password under 8 characters — or the user ID is already taken (` + "`" + `USER_ID_ALREADY_EXISTS` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Issues a new card linked to an active account owned by the authenticated requester.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "Issue a card",
                "parameters": [
                    {
                        "description": "Linked account and card brand",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.IssueCardRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The card was issued.",
                        "schema": {
                            "$ref": "#/definitions/http.CardResponse"
                        }
                    },
                    "400": {
                        "description": "One of: request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `), or the linked account is not active (` + "`" + `CARD_ISSUE_REQUIRES_ACTIVE_ACCOUNT` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists with the given ` + "`" + `accountId` + "`" + ` for this requester (` + "`" + `LINKED_ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/{cardId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the card only if it belongs to the authenticated requester.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "Look up a card",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The card ID",
                        "name": "cardId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The card was found.",
                        "schema": {
                            "$ref": "#/definitions/http.CardResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No card exists with the given ` + "`" + `cardId` + "`" + ` for this requester (` + "`" + `CARD_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Reports whether the process itself is alive. Always returns 200, even while the process is shutting down — an orchestrator should use ` + "`" + `ready` + "`" + `, not this, to decide whether to route traffic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "The process is alive — returns 200 even while shutting down."
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Reports whether the process is ready to accept new requests. Used by an orchestrator to stop routing traffic during graceful shutdown.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "Ready to accept new requests."
                    },
                    "503": {
                        "description": "Shutdown has started and new requests are no longer accepted."
                    }
                }
            }
        },
        "/payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated requester's payments, newest first, paginated with ` + "`" + `page` + "`" + `/` + "`" + `take` + "`" + `. Out-of-range ` + "`" + `page` + "`" + `/` + "`" + `take` + "`" + ` values fall back to their defaults rather than failing.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "List the requester's payments",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page number, starting at 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "take",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The payment list was found.",
                        "schema": {
                            "$ref": "#/definitions/http.GetPaymentsResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Charges an active card linked to an active account with sufficient balance. The account balance is debited asynchronously once the payment completes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Create a payment",
                "parameters": [
                    {
                        "description": "Card to charge and amount",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The payment was created.",
                        "schema": {
                            "$ref": "#/definitions/http.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "One of: request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `), the card is not active (` + "`" + `PAYMENT_REQUIRES_ACTIVE_CARD` + "`" + `), the linked account is not active (` + "`" + `PAYMENT_REQUIRES_ACTIVE_ACCOUNT` + "`" + `), or the account balance is insufficient (` + "`" + `INSUFFICIENT_BALANCE` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "One of: no card exists with the given ` + "`" + `cardId` + "`" + ` (` + "`" + `LINKED_CARD_NOT_FOUND` + "`" + `), or the card's linked account could not be found (` + "`" + `LINKED_ACCOUNT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payments/{paymentId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the payment only if it belongs to the authenticated requester.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Look up a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The payment ID",
                        "name": "paymentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The payment was found.",
                        "schema": {
                            "$ref": "#/definitions/http.PaymentResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No payment exists with the given ` + "`" + `paymentId` + "`" + ` for this requester (` + "`" + `PAYMENT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payments/{paymentId}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancels a completed payment before it is refunded.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Cancel a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The payment ID",
                        "name": "paymentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancellation reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CancelPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "The payment was cancelled."
                    },
                    "400": {
                        "description": "One of: request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `), or only a completed payment can be cancelled (` + "`" + `PAYMENT_CANCEL_REQUIRES_COMPLETED_PAYMENT` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No payment exists with the given ` + "`" + `paymentId` + "`" + ` (` + "`" + `PAYMENT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payments/{paymentId}/refunds": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the refunds requested against a payment, newest first, paginated with ` + "`" + `page` + "`" + `/` + "`" + `take` + "`" + `. Out-of-range ` + "`" + `page` + "`" + `/` + "`" + `take` + "`" + ` values fall back to their defaults rather than failing.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "List a payment's refunds",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The payment ID",
                        "name": "paymentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page number, starting at 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "take",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The refund list was found.",
                        "schema": {
                            "$ref": "#/definitions/http.GetRefundsResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No payment exists with the given ` + "`" + `paymentId` + "`" + ` (` + "`" + `PAYMENT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Requests a refund for a payment. Eligibility is judged synchronously (` + "`" + `APPROVED` + "`" + `/` + "`" + `REJECTED` + "`" + `); an approved refund is credited back to the account asynchronously.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Request a refund",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The payment ID",
                        "name": "paymentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Refund amount and reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.RequestRefundRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The refund request was recorded (its ` + "`" + `status` + "`" + ` may still be ` + "`" + `REJECTED` + "`" + ` — check the response body, not just the HTTP status).",
                        "schema": {
                            "$ref": "#/definitions/http.RefundResponse"
                        }
                    },
                    "400": {
                        "description": "Request validation failed (` + "`" + `VALIDATION_FAILED` + "`" + `) — e.g. a non-positive amount or missing reason.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The bearer token is missing, malformed, or invalid.",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No payment exists with the given ` + "`" + `paymentId` + "`" + ` (` + "`" + `PAYMENT_NOT_FOUND` + "`" + `).",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.CancelPaymentRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "description": "Why the payment is being cancelled.",
                    "type": "string"
                }
            }
        },
        "http.CardResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "description": "The account this card is linked to.",
                    "type": "string"
                },
                "brand": {
                    "description": "The card brand (e.g. ` + "`" + `VISA` + "`" + `, ` + "`" + `MASTER` + "`" + `).",
                    "type": "string"
                },
                "cardId": {
                    "description": "The card's ID.",
                    "type": "string"
                },
                "createdAt": {
                    "description": "When the card was issued.",
                    "type": "string"
                },
                "ownerId": {
                    "description": "The card owner's user ID.",
                    "type": "string"
                },
                "status": {
                    "description": "The card status (` + "`" + `ACTIVE` + "`" + `, ` + "`" + `SUSPENDED` + "`" + `, or ` + "`" + `CANCELLED` + "`" + `).",
                    "type": "string"
                }
            }
        },
        "http.CreateAccountRequest": {
            "type": "object",
            "properties": {
                "currency": {
                    "description": "The account's currency code (e.g. ` + "`" + `KRW` + "`" + `, ` + "`" + `USD` + "`" + `). Fixed for the account's lifetime.",
                    "type": "string"
                },
                "email": {
                    "description": "The account owner's email address. Used as the destination for notification emails.",
                    "type": "string"
                }
            }
        },
        "http.CreateAccountResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "description": "The newly created account's ID.",
                    "type": "string"
                },
                "balance": {
                    "description": "The account balance. Always 0 immediately after creation.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.MoneyResponse"
                        }
                    ]
                },
                "createdAt": {
                    "description": "When the account was created.",
                    "type": "string"
                },
                "email": {
                    "description": "The account owner's email address.",
                    "type": "string"
                },
                "ownerId": {
                    "description": "The authenticated requester's user ID.",
                    "type": "string"
                },
                "status": {
                    "description": "The account status (` + "`" + `ACTIVE` + "`" + `, ` + "`" + `SUSPENDED` + "`" + `, or ` + "`" + `CLOSED` + "`" + `).",
                    "type": "string"
                }
            }
        },
        "http.CreatePaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "The amount to charge. Must be a positive integer.",
                    "type": "integer"
                },
                "cardId": {
                    "description": "The active card to charge. Must be linked to an active account with sufficient balance.",
                    "type": "string"
                }
            }
        },
        "http.DepositRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "The amount to credit. Must be a positive integer.",
                    "type": "integer"
                }
            }
        },
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "A stable, machine-readable error code the client can branch on (e.g. ` + "`" + `ACCOUNT_NOT_FOUND` + "`" + `). Unlike ` + "`" + `message` + "`" + `, this never changes wording.",
                    "type": "string"
                },
                "error": {
                    "description": "The standard HTTP status text for ` + "`" + `statusCode` + "`" + ` (e.g. ` + "`" + `Not Found` + "`" + `).",
                    "type": "string"
                },
                "message": {
                    "description": "A human-readable description of the error.",
                    "type": "string"
                },
                "statusCode": {
                    "description": "The HTTP status code.",
                    "type": "integer"
                }
            }
        },
        "http.GetAccountResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "description": "The account's ID.",
                    "type": "string"
                },
                "balance": {
                    "description": "The current account balance.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.MoneyResponse"
                        }
                    ]
                },
                "createdAt": {
                    "description": "When the account was created.",
                    "type": "string"
                },
                "email": {
                    "description": "The account owner's email address.",
                    "type": "string"
                },
                "ownerId": {
                    "description": "The account owner's user ID.",
                    "type": "string"
                },
                "status": {
                    "description": "The account status (` + "`" + `ACTIVE` + "`" + `, ` + "`" + `SUSPENDED` + "`" + `, or ` + "`" + `CLOSED` + "`" + `).",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "When the account was last modified.",
                    "type": "string"
                }
            }
        },
        "http.GetPaymentsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "The total number of payments matching the filter (not just the current page's size).",
                    "type": "integer"
                },
                "payments": {
                    "description": "The requester's payments, newest first.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.PaymentResponse"
                    }
                }
            }
        },
        "http.GetRefundsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "The total number of refunds matching the filter (not just the current page's size).",
                    "type": "integer"
                },
                "refunds": {
                    "description": "The refunds requested against the payment, newest first.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.RefundResponse"
                    }
                }
            }
        },
        "http.GetTransactionsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "The total number of transactions matching the filter (not just the current page's size).",
                    "type": "integer"
                },
                "transactions": {
                    "description": "The account's transactions, newest first.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.TransactionSummaryResponse"
                    }
                }
            }
        },
        "http.IssueCardRequest": {
            "type": "object",
            "properties": {
                "accountId": {
                    "description": "The active account to link the card to. Must be owned by the authenticated requester.",
                    "type": "string"
                },
                "brand": {
                    "description": "The card brand (e.g. ` + "`" + `VISA` + "`" + `, ` + "`" + `MASTER` + "`" + `).",
                    "type": "string"
                }
            }
        },
        "http.MoneyResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "The amount, in the currency's smallest unit (no decimal places).",
                    "type": "integer"
                },
                "currency": {
                    "description": "The currency code (e.g. ` + "`" + `KRW` + "`" + `, ` + "`" + `USD` + "`" + `).",
                    "type": "string"
                }
            }
        },
        "http.PaymentResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "description": "The account debited (asynchronously) for this payment.",
                    "type": "string"
                },
                "amount": {
                    "description": "The charged amount.",
                    "type": "integer"
                },
                "cardId": {
                    "description": "The card used for this payment.",
                    "type": "string"
                },
                "createdAt": {
                    "description": "When the payment was created.",
                    "type": "string"
                },
                "ownerId": {
                    "description": "The payment owner's user ID.",
                    "type": "string"
                },
                "paymentId": {
                    "description": "The payment's ID.",
                    "type": "string"
                },
                "status": {
                    "description": "The payment status (` + "`" + `COMPLETED` + "`" + ` or ` + "`" + `CANCELLED` + "`" + `).",
                    "type": "string"
                }
            }
        },
        "http.RefundResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "The requested refund amount.",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "When the refund was requested.",
                    "type": "string"
                },
                "decisionNote": {
                    "description": "Why the refund was rejected. Only present when ` + "`" + `status` + "`" + ` is ` + "`" + `REJECTED` + "`" + `.",
                    "type": "string"
                },
                "paymentId": {
                    "description": "The payment this refund was requested against.",
                    "type": "string"
                },
                "reason": {
                    "description": "Why the refund was requested.",
                    "type": "string"
                },
                "refundId": {
                    "description": "The refund request's ID.",
                    "type": "string"
                },
                "status": {
                    "description": "The refund status (` + "`" + `APPROVED` + "`" + `, ` + "`" + `REJECTED` + "`" + `, or ` + "`" + `COMPLETED` + "`" + `) — check this, not just the HTTP status, since a rejection is still a 201 response.",
                    "type": "string"
                }
            }
        },
        "http.RequestRefundRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "The amount to refund. Must be a positive integer not exceeding the original payment amount.",
                    "type": "integer"
                },
                "reason": {
                    "description": "Why the refund is being requested.",
                    "type": "string"
                }
            }
        },
        "http.SignInRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "The account password.",
                    "type": "string"
                },
                "userId": {
                    "description": "The registered user ID.",
                    "type": "string"
                }
            }
        },
        "http.SignInResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "description": "A JWT bearer token. Send it as ` + "`" + `Authorization: Bearer \u003caccessToken\u003e` + "`" + ` on subsequent requests.",
                    "type": "string"
                }
            }
        },
        "http.SignUpRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "The account password. Must be at least 8 characters.",
                    "type": "string"
                },
                "userId": {
                    "description": "The user ID to register. Must be unique.",
                    "type": "string"
                }
            }
        },
        "http.TransactionResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "description": "The account this transaction belongs to.",
                    "type": "string"
                },
                "amount": {
                    "description": "The transaction amount.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.MoneyResponse"
                        }
                    ]
                },
                "createdAt": {
                    "description": "When the transaction was recorded.",
                    "type": "string"
                },
                "transactionId": {
                    "description": "The transaction record's ID.",
                    "type": "string"
                },
                "type": {
                    "description": "The transaction type (` + "`" + `DEPOSIT` + "`" + `, ` + "`" + `WITHDRAWAL` + "`" + `, or ` + "`" + `INTEREST` + "`" + `).",
                    "type": "string"
                }
            }
        },
        "http.TransactionSummaryResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "The transaction amount.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.MoneyResponse"
                        }
                    ]
                },
                "createdAt": {
                    "description": "When the transaction was recorded.",
                    "type": "string"
                },
                "transactionId": {
                    "description": "The transaction record's ID.",
                    "type": "string"
                },
                "type": {
                    "description": "The transaction type (` + "`" + `DEPOSIT` + "`" + `, ` + "`" + `WITHDRAWAL` + "`" + `, or ` + "`" + `INTEREST` + "`" + `).",
                    "type": "string"
                }
            }
        },
        "http.TransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "The amount to transfer. Must be a positive integer not exceeding the source account's balance.",
                    "type": "integer"
                },
                "targetAccountId": {
                    "description": "The account ID to transfer into. Must differ from the source account in the URL path.",
                    "type": "string"
                }
            }
        },
        "http.TransferResponse": {
            "type": "object",
            "properties": {
                "sourceTransaction": {
                    "description": "The ` + "`" + `WITHDRAWAL` + "`" + ` transaction recorded on the source account.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.TransactionResponse"
                        }
                    ]
                },
                "targetTransaction": {
                    "description": "The ` + "`" + `DEPOSIT` + "`" + ` transaction recorded on the target account.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.TransactionResponse"
                        }
                    ]
                },
                "transferId": {
                    "description": "Correlates the source and target transactions raised by this single transfer.",
                    "type": "string"
                }
            }
        },
        "http.WithdrawRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "The amount to debit. Must be a positive integer not exceeding the current balance.",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the JWT access token issued by ` + "`" + `POST /auth/sign-in` + "`" + `.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Account Service API",
	Description:      "API documentation for the DDD-based Account domain example service (Account/Card/Payment/Refund/Credential Bounded Contexts). Generated from the @-annotations above each handler in internal/interface/http/ by swag (docs/architecture/api-documentation.md) — never hand-edited.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
