from enum import Enum


class CardErrorCode(str, Enum):
    CARD_NOT_FOUND = "CARD_NOT_FOUND"
    LINKED_ACCOUNT_NOT_FOUND = "LINKED_ACCOUNT_NOT_FOUND"
    CARD_ISSUE_REQUIRES_ACTIVE_ACCOUNT = "CARD_ISSUE_REQUIRES_ACTIVE_ACCOUNT"
    CANCELLED_CARD_CANNOT_BE_SUSPENDED = "CANCELLED_CARD_CANNOT_BE_SUSPENDED"
    CARD_ALREADY_SUSPENDED = "CARD_ALREADY_SUSPENDED"
    CARD_ALREADY_CANCELLED = "CARD_ALREADY_CANCELLED"
