from enum import Enum


class AccountErrorCode(str, Enum):
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND"
    INVALID_AMOUNT = "INVALID_AMOUNT"
    INVALID_MONEY_AMOUNT = "INVALID_MONEY_AMOUNT"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    DEPOSIT_REQUIRES_ACTIVE_ACCOUNT = "DEPOSIT_REQUIRES_ACTIVE_ACCOUNT"
    WITHDRAW_REQUIRES_ACTIVE_ACCOUNT = "WITHDRAW_REQUIRES_ACTIVE_ACCOUNT"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    SUSPEND_REQUIRES_ACTIVE_ACCOUNT = "SUSPEND_REQUIRES_ACTIVE_ACCOUNT"
    REACTIVATE_REQUIRES_SUSPENDED_ACCOUNT = "REACTIVATE_REQUIRES_SUSPENDED_ACCOUNT"
    ACCOUNT_ALREADY_CLOSED = "ACCOUNT_ALREADY_CLOSED"
    ACCOUNT_BALANCE_NOT_ZERO = "ACCOUNT_BALANCE_NOT_ZERO"
    VALIDATION_FAILED = "VALIDATION_FAILED"  # Pydantic 검증 실패 전용, 고정값
