-- Monthly card statement delivery (scheduling.md Feature 2) — a Level 2 Ledger field used to
-- determine "has this month's notice already been sent" (see card/domain/Card.shouldSendStatement()).
-- Stores a YearMonth as a "yyyy-MM" string.
ALTER TABLE card ADD COLUMN last_statement_sent_month VARCHAR(7);

-- A Card BC-specific send-history table with the same structure as account's sent_email — just as
-- the Card BC has its own NotificationService implementation, it also keeps its own send history
-- (see the "default is in-domain" principle in domain-service.md).
CREATE TABLE card_sent_email (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sent_email_id VARCHAR(255) NOT NULL,
    card_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    ses_message_id VARCHAR(255) NOT NULL,
    sent_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_card_sent_email_sent_email_id UNIQUE (sent_email_id)
);

CREATE INDEX idx_card_sent_email_card_id ON card_sent_email (card_id);
