-- 월간 카드 사용내역 발송(scheduling.md Feature 2) — "이번 달 안내를 이미 보냈는지" 판단하는 Level 2
-- Ledger 필드다(card/domain/Card.shouldSendStatement() 참고). YearMonth를 "yyyy-MM" 문자열로 저장한다.
ALTER TABLE card ADD COLUMN last_statement_sent_month VARCHAR(7);

-- account의 sent_email과 동일한 구조의 Card BC 전용 발송 이력 테이블 — Card BC가 자신의
-- NotificationService 구현체를 따로 갖는 것과 마찬가지로 발송 이력도 별도로 둔다(domain-service.md "배치
-- 원칙").
CREATE TABLE card_sent_email (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sent_email_id VARCHAR(255) NOT NULL,
    card_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    ses_message_id VARCHAR(255) NOT NULL,
    sent_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_card_sent_email_sent_email_id UNIQUE (sent_email_id)
);

CREATE INDEX idx_card_sent_email_card_id ON card_sent_email (card_id);
