-- The read-model table account.analyze-monthly-spending's ETL writes to, one row per
-- (accountId, analysisMonth) — the unique constraint is the idempotency backstop, the same role
-- as the card_sent_email uniqueness check.
CREATE TABLE spending_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    analysis_month VARCHAR(7) NOT NULL,
    total_amount BIGINT NOT NULL,
    transaction_count BIGINT NOT NULL,
    average_amount BIGINT NOT NULL,
    change_from_previous_month INTEGER NOT NULL,
    trend VARCHAR(20) NOT NULL CHECK (trend IN ('INCREASING', 'DECREASING', 'STABLE')),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_spending_analysis_analysis_id UNIQUE (analysis_id),
    CONSTRAINT uk_spending_analysis_account_month UNIQUE (account_id, analysis_month)
);

CREATE INDEX idx_spending_analysis_account_id ON spending_analysis (account_id);
