-- The read-model table account.forecast-spending's ETL writes to, one row per
-- (accountId, forecastMonth) — the unique constraint is the idempotency backstop, the same role
-- as spending_analysis's uniqueness check.
CREATE TABLE spending_forecast (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    forecast_month VARCHAR(7) NOT NULL,
    predicted_amount BIGINT NOT NULL,
    confidence VARCHAR(10) NOT NULL CHECK (confidence IN ('LOW', 'MEDIUM', 'HIGH')),
    history_months_used INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_spending_forecast_forecast_id UNIQUE (forecast_id),
    CONSTRAINT uk_spending_forecast_account_month UNIQUE (account_id, forecast_month)
);

CREATE INDEX idx_spending_forecast_account_id ON spending_forecast (account_id);
