CREATE TABLE sent_email (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sent_email_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    ses_message_id VARCHAR(255) NOT NULL,
    sent_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_sent_email_sent_email_id UNIQUE (sent_email_id)
);
