CREATE TABLE card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    owner_id VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CANCELLED')),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_card_card_id UNIQUE (card_id)
);

CREATE INDEX idx_card_account_id ON card (account_id);
CREATE INDEX idx_card_owner_id ON card (owner_id);
