CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR(255) NOT NULL,
    card_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    owner_id VARCHAR(255) NOT NULL,
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_payment_payment_id UNIQUE (payment_id)
);

CREATE INDEX idx_payment_owner_id ON payment (owner_id);
CREATE INDEX idx_payment_card_id ON payment (card_id);
CREATE INDEX idx_payment_account_id ON payment (account_id);

CREATE TABLE refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id VARCHAR(255) NOT NULL,
    payment_id VARCHAR(255) NOT NULL,
    amount BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED')),
    decision_note VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_refund_refund_id UNIQUE (refund_id)
);

CREATE INDEX idx_refund_payment_id ON refund (payment_id);

-- Payment BC의 Integration Event(payment.completed.v1 등)에 대한 Account BC의 반응이 at-least-once
-- 재수신에도 같은 거래를 중복 생성하지 않도록 하는 멱등성 판단 키다(Level 2 Ledger, domain-events.md 참고).
ALTER TABLE transactions ADD COLUMN reference_id VARCHAR(255);

-- (reference_id, type) 조합에 한해서만 유니크 — 결제완료(WITHDRAWAL)와 그 결제취소 보상 크레딧(DEPOSIT)은
-- 같은 paymentId를 reference_id로 공유하는 서로 다른 거래이므로 reference_id 단독 유니크는 보상 크레딧 삽입
-- 자체를 막아버린다. 동시에 도착한 중복 Integration Event가 애플리케이션의 체크
-- (AccountRepository.hasTransactionWithReference)를 통과해버리는 극히 짧은 race를 DB 제약으로 한 번 더
-- 막는다(Level 2 Ledger의 방어선을 이중화).
CREATE UNIQUE INDEX uk_transactions_reference_id_type ON transactions (reference_id, type) WHERE reference_id IS NOT NULL;
