CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR(255) NOT NULL,
    card_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    owner_id VARCHAR(255) NOT NULL,
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_payment_payment_id UNIQUE (payment_id)
);

CREATE INDEX idx_payment_owner_id ON payment (owner_id);
CREATE INDEX idx_payment_card_id ON payment (card_id);
CREATE INDEX idx_payment_account_id ON payment (account_id);

CREATE TABLE refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id VARCHAR(255) NOT NULL,
    payment_id VARCHAR(255) NOT NULL,
    amount BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED')),
    decision_note VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_refund_refund_id UNIQUE (refund_id)
);

CREATE INDEX idx_refund_payment_id ON refund (payment_id);

-- The idempotency key that keeps the Account BC's reaction to a Payment BC Integration Event
-- (payment.completed.v1, etc) from creating a duplicate transaction even under at-least-once
-- redelivery (Level 2 Ledger, see domain-events.md).
ALTER TABLE transactions ADD COLUMN reference_id VARCHAR(255);

-- Unique only on the (reference_id, type) combination — a payment completion (WITHDRAWAL) and its
-- payment-cancellation compensating credit (DEPOSIT) are different transactions that share the
-- same paymentId as reference_id, so a unique constraint on reference_id alone would block the
-- compensating credit insert itself. This also blocks, via a DB constraint, the extremely narrow
-- race where a duplicate Integration Event arriving at the same time slips past the application's
-- check (AccountRepository.hasTransactionWithReference) — doubling up Level 2 Ledger's defense.
CREATE UNIQUE INDEX uk_transactions_reference_id_type ON transactions (reference_id, type) WHERE reference_id IS NOT NULL;
