// PaymentErrorMessage의 모든 항목에 1:1로 매핑되는 코드
// (docs/architecture/error-handling.md 참고). REFUND_*_REQUIRES_*_REFUND와
// PAYMENT_*_REQUIRES_PENDING_PAYMENT는 Application 레이어가 이미 올바른 선행 상태를
// 보장한 뒤에만 호출하므로(예: RefundEligibilityService가 REQUESTED 상태만 approve()/
// reject()에 넘김) 현재 REST 표면에서는 도달하지 않는 방어적 코드다 — Payment.fail()/
// Refund.complete()처럼 아직 어떤 Command도 연결하지 않은 도메인 메서드의 가드와
// 짝을 이룬다.
export enum PaymentErrorCode {
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  LINKED_CARD_NOT_FOUND = 'LINKED_CARD_NOT_FOUND',
  PAYMENT_REQUIRES_ACTIVE_CARD = 'PAYMENT_REQUIRES_ACTIVE_CARD',
  LINKED_ACCOUNT_NOT_FOUND = 'LINKED_ACCOUNT_NOT_FOUND',
  PAYMENT_REQUIRES_ACTIVE_ACCOUNT = 'PAYMENT_REQUIRES_ACTIVE_ACCOUNT',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  PAYMENT_CANCEL_REQUIRES_COMPLETED_PAYMENT = 'PAYMENT_CANCEL_REQUIRES_COMPLETED_PAYMENT',
  REFUND_REQUIRES_COMPLETED_PAYMENT = 'REFUND_REQUIRES_COMPLETED_PAYMENT',
  REFUND_AMOUNT_EXCEEDS_PAYMENT = 'REFUND_AMOUNT_EXCEEDS_PAYMENT',
  PAYMENT_COMPLETE_REQUIRES_PENDING_PAYMENT = 'PAYMENT_COMPLETE_REQUIRES_PENDING_PAYMENT',
  PAYMENT_FAIL_REQUIRES_PENDING_PAYMENT = 'PAYMENT_FAIL_REQUIRES_PENDING_PAYMENT',
  REFUND_APPROVE_REQUIRES_REQUESTED_REFUND = 'REFUND_APPROVE_REQUIRES_REQUESTED_REFUND',
  REFUND_REJECT_REQUIRES_REQUESTED_REFUND = 'REFUND_REJECT_REQUIRES_REQUESTED_REFUND',
  REFUND_COMPLETE_REQUIRES_APPROVED_REFUND = 'REFUND_COMPLETE_REQUIRES_APPROVED_REFUND',
}
