export enum PaymentErrorMessage {
  'Payment not found.' = 'Payment not found.',
  'The card to link could not be found.' = 'The card to link could not be found.',
  'Only an active card can be used for payment.' = 'Only an active card can be used for payment.',
  'The linked account could not be found.' = 'The linked account could not be found.',
  'Only an active account can be used for payment.' = 'Only an active account can be used for payment.',
  'Payment cannot be made due to insufficient account balance.' = 'Payment cannot be made due to insufficient account balance.',
  'Only a completed payment can be cancelled.' = 'Only a completed payment can be cancelled.',
  'A refund can only be requested for a completed payment.' = 'A refund can only be requested for a completed payment.',
  'The refund amount cannot exceed the payment amount.' = 'The refund amount cannot exceed the payment amount.',
  'Can only be marked completed from the pending state.' = 'Can only be marked completed from the pending state.',
  'Can only be marked failed from the pending state.' = 'Can only be marked failed from the pending state.',
  'Can only be approved from the requested state.' = 'Can only be approved from the requested state.',
  'Can only be rejected from the requested state.' = 'Can only be rejected from the requested state.',
  'Only an approved refund can be marked completed.' = 'Only an approved refund can be marked completed.',
}
