// Codes mapped 1:1 to every entry in PaymentErrorMessage
// (see docs/architecture/error-handling.md). REFUND_*_REQUIRES_*_REFUND and
// PAYMENT_*_REQUIRES_PENDING_PAYMENT are only ever called once the Application layer has
// already guaranteed the correct preceding state (e.g. RefundEligibilityService only passes
// a REQUESTED-state refund into approve()/reject()), so they're defensive code that the
// current REST surface never actually reaches — they're paired with the guards of domain
// methods like Payment.fail()/Refund.complete() that no Command wires up yet.
export enum PaymentErrorCode {
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  LINKED_CARD_NOT_FOUND = 'LINKED_CARD_NOT_FOUND',
  PAYMENT_REQUIRES_ACTIVE_CARD = 'PAYMENT_REQUIRES_ACTIVE_CARD',
  LINKED_ACCOUNT_NOT_FOUND = 'LINKED_ACCOUNT_NOT_FOUND',
  PAYMENT_REQUIRES_ACTIVE_ACCOUNT = 'PAYMENT_REQUIRES_ACTIVE_ACCOUNT',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  PAYMENT_CANCEL_REQUIRES_COMPLETED_PAYMENT = 'PAYMENT_CANCEL_REQUIRES_COMPLETED_PAYMENT',
  REFUND_REQUIRES_COMPLETED_PAYMENT = 'REFUND_REQUIRES_COMPLETED_PAYMENT',
  REFUND_AMOUNT_EXCEEDS_PAYMENT = 'REFUND_AMOUNT_EXCEEDS_PAYMENT',
  PAYMENT_COMPLETE_REQUIRES_PENDING_PAYMENT = 'PAYMENT_COMPLETE_REQUIRES_PENDING_PAYMENT',
  PAYMENT_FAIL_REQUIRES_PENDING_PAYMENT = 'PAYMENT_FAIL_REQUIRES_PENDING_PAYMENT',
  REFUND_APPROVE_REQUIRES_REQUESTED_REFUND = 'REFUND_APPROVE_REQUIRES_REQUESTED_REFUND',
  REFUND_REJECT_REQUIRES_REQUESTED_REFUND = 'REFUND_REJECT_REQUIRES_REQUESTED_REFUND',
  REFUND_COMPLETE_REQUIRES_APPROVED_REFUND = 'REFUND_COMPLETE_REQUIRES_APPROVED_REFUND',
}
