CREATE TABLE refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id VARCHAR(255) NOT NULL,
    payment_id VARCHAR(255) NOT NULL,
    amount BIGINT NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED')),
    decision_note VARCHAR(1000),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_refunds_refund_id UNIQUE (refund_id)
);

CREATE INDEX idx_refunds_payment_id ON refunds (payment_id);
