-- Task Outbox (scheduling.md) — for the same reason as Domain Event's outbox_events (preventing
-- dual-write), Tasks enqueued by the Scheduler are also written to this table first, and
-- TaskOutboxPoller independently publishes them to SQS (FIFO). A UNIQUE constraint on
-- deduplication_id prevents duplicate row insertion at the DB level even when multiple instances
-- run the same Cron concurrently for the same date/month (a guarantee with broader scope than
-- SQS FIFO's 5-minute deduplication window).
CREATE TABLE task_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(255) NOT NULL,
    task_type VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    group_id VARCHAR(255) NOT NULL,
    deduplication_id VARCHAR(255) NOT NULL,
    processed BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_task_outbox_task_id UNIQUE (task_id),
    CONSTRAINT uk_task_outbox_deduplication_id UNIQUE (deduplication_id)
);

CREATE INDEX idx_task_outbox_processed_created_at ON task_outbox (processed, created_at);
