-- Task Outbox(scheduling.md) — Domain Event의 outbox_events와 같은 이유(dual-write 방지)로,
-- Scheduler가 적재하는 Task도 이 테이블에 먼저 쓰고 TaskOutboxPoller가 독립적으로 SQS(FIFO)에
-- 발행한다. deduplication_id에 UNIQUE 제약을 걸어, 여러 인스턴스가 같은 날짜/월에 동시에 Cron을
-- 실행해도 DB 레벨에서 중복 행 적재 자체를 막는다(SQS FIFO의 5분 중복 제거 윈도우보다 더 넓은
-- 범위의 보장).
CREATE TABLE task_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(255) NOT NULL,
    task_type VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    group_id VARCHAR(255) NOT NULL,
    deduplication_id VARCHAR(255) NOT NULL,
    processed BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_task_outbox_task_id UNIQUE (task_id),
    CONSTRAINT uk_task_outbox_deduplication_id UNIQUE (deduplication_id)
);

CREATE INDEX idx_task_outbox_processed_created_at ON task_outbox (processed, created_at);
