-- The read-model table account.analyze-monthly-spending's ETL writes to, one row per
-- (accountId, analysisMonth) — the unique index is the idempotency backstop alongside the explicit
-- hasAnalysis() precheck in AnalyzeMonthlySpendingService.
CREATE TABLE spending_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    analysis_month VARCHAR(7) NOT NULL,
    total_amount BIGINT NOT NULL,
    transaction_count BIGINT NOT NULL,
    average_amount BIGINT NOT NULL,
    change_from_previous_month BIGINT NOT NULL,
    trend VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_spending_analysis_analysis_id UNIQUE (analysis_id),
    CONSTRAINT uk_spending_analysis_account_id_analysis_month UNIQUE (account_id, analysis_month)
);
