-- The read-model table account.forecast-spending's batch job writes to, one row per
-- (accountId, forecastMonth) — the unique constraint is the idempotency backstop alongside the
-- explicit hasForecast() precheck in ForecastSpendingService.
CREATE TABLE spending_forecast (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    forecast_month VARCHAR(7) NOT NULL,
    predicted_amount BIGINT NOT NULL,
    confidence VARCHAR(10) NOT NULL,
    history_months_used INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_spending_forecast_forecast_id UNIQUE (forecast_id),
    CONSTRAINT uk_spending_forecast_account_id_forecast_month UNIQUE (account_id, forecast_month)
);
