CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('DEPOSIT', 'WITHDRAWAL')),
    amount BIGINT,
    currency VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_transactions_transaction_id UNIQUE (transaction_id)
);
