CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    owner_id VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CANCELLED')),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_cards_card_id UNIQUE (card_id)
);

CREATE INDEX idx_cards_account_id_status ON cards (account_id, status);
