CREATE TABLE credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_credentials_credential_id UNIQUE (credential_id),
    CONSTRAINT uk_credentials_user_id UNIQUE (user_id)
);
