CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR(255) NOT NULL,
    card_id VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    owner_id VARCHAR(255) NOT NULL,
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_payments_payment_id UNIQUE (payment_id)
);

CREATE INDEX idx_payments_owner_id ON payments (owner_id);
