package com.example.accountservice.account.domain

enum class AccountErrorCode {
    ACCOUNT_NOT_FOUND,
    INVALID_AMOUNT,
    INVALID_MONEY_AMOUNT,
    CURRENCY_MISMATCH,
    DEPOSIT_REQUIRES_ACTIVE_ACCOUNT,
    WITHDRAW_REQUIRES_ACTIVE_ACCOUNT,
    INSUFFICIENT_BALANCE,
    SUSPEND_REQUIRES_ACTIVE_ACCOUNT,
    REACTIVATE_REQUIRES_SUSPENDED_ACCOUNT,
    ACCOUNT_ALREADY_CLOSED,
    ACCOUNT_BALANCE_NOT_ZERO,
    DELETE_REQUIRES_CLOSED_ACCOUNT,
    TRANSFER_SAME_ACCOUNT,
}
