package harness.rules;

import harness.Finding;
import harness.RuleResult;

import java.io.File;
import java.util.regex.Pattern;

import static harness.JavaFiles.collectJavaFiles;
import static harness.JavaFiles.nameWithoutExtension;
import static harness.JavaFiles.readText;
import static harness.JavaFiles.relTo;

/**
 * [24] Aggregate ID format — only a 32-character hex string (no hyphens) is allowed.
 * {@code UUID.randomUUID().toString()} returns a 36-character string containing 4
 * hyphens, so it must not be used as-is for an Aggregate ID — the hyphens must be
 * stripped (aggregate-id.md — "an Aggregate ID is a 32-character hex string, generated by
 * stripping the hyphens from a UUID").
 *
 * <p>This repository centralizes ID generation into a single shared utility, {@code
 * common/IdGenerator.java}, so this is a single-file rule that checks only that one file
 * — if each Aggregate generated its own ID, a per-domain repeated check would be needed,
 * but in the current structure this utility is the sole generation point.
 */
public final class AggregateIdFormat {
    private AggregateIdFormat() {
    }

    private static final Pattern RANDOM_UUID = Pattern.compile("UUID\\s*\\.\\s*randomUUID\\s*\\(\\s*\\)");
    private static final Pattern STRIP_HYPHENS =
        Pattern.compile("\\.replace(?:All)?\\s*\\(\\s*\"-\"\\s*,\\s*\"\"\\s*\\)");

    public static RuleResult check(String rootPath) {
        File root = new File(rootPath);
        RuleResult result = new RuleResult("aggregate-id-format");

        File idGenerator = null;
        for (File f : collectJavaFiles(root)) {
            if (nameWithoutExtension(f).equals("IdGenerator")) {
                idGenerator = f;
                break;
            }
        }

        if (idGenerator == null) {
            result.add(Finding.skip("No common/IdGenerator.java (ID-generation utility)"));
            return result;
        }

        String rel = relTo(idGenerator, root);
        String code = stripComments(readText(idGenerator));

        if (!RANDOM_UUID.matcher(code).find()) {
            result.add(Finding.fail(rel,
                "Could not find a UUID.randomUUID() call — could not confirm the Aggregate ID generation mechanism (aggregate-id.md)"));
            return result;
        }

        if (STRIP_HYPHENS.matcher(code).find()) {
            result.add(Finding.pass(rel + " (confirmed the UUID's hyphens are stripped — produces a 32-character hex string)"));
        } else {
            result.add(Finding.fail(rel,
                "Does not strip the hyphens from UUID.randomUUID().toString() — must return a 32-character hex string, not a 36-character hyphenated string (.replace(\"-\", \"\") required, aggregate-id.md)"));
        }

        return result;
    }

    private static String stripComments(String content) {
        return content.replaceAll("/\\*[\\s\\S]*?\\*/", "").replaceAll("//.*", "");
    }
}
